name: Dotfiles Vim Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Vim
        run: sudo apt-get update && sudo apt-get install -y vim

      - name: Run Vim Tests
        # 2>&1 ensures we see the output in the GitHub logs
        run: vim -Es -u NONE -S .vim/tests/test_runner.vim 2>&1
